#アプリを動かすための複数のコンテナを一括管理する
#例えば、web(Rails),db(PostgreSQL), selenium(テスト用ブラウザ)を同時に立ち上げて、それぞれをどう繋ぐかを定義
services: 
  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2g # メモリ不足を防ぐためのおまじない
    ports:
      - "4444:4444" # Selenium Gridのポート

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - selenium
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-} # .envファイルからAPIキーを読み込む
      DOCKER_CONTAINER: "true" # Dockerコンテナ内で実行されていることを示す
      SELENIUM_URL: http://selenium:4444/wd/hub # webコンテナからseleniumコンテナに接続するためのURL
      LINE_CHANNEL_ID: ${LINE_CHANNEL_ID:-} 
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET:-}
      DISABLE_SPRING: 1 # ファイル変更の検知問題を避けるためにSpringを無効化

    # docker-compose.ymlで定義したcronコンテナはconfig/schedule.rbの設定に沿ってコマンド実行
    # lib/tasks/notifications.rake にはtask send_due: :environment とかいてある
    # これによってRakeタスクは実行前にRailsアプリ全体を読み込む。
    # これは、bin/rails consoleを起動したときと同じ状態。
    # environment以下のコマンドはその時に必要とされる情報
    cron:
      build: .
      command: /app/entrypoint-cron.sh
      volumes:
        - .:/app
        - bundle:/usr/local/bundle
      depends_on:
        - db
      environment:
        DATABASE_HOST: db
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: password
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-}
        DOCKER_CONTAINER: "true"
        DISABLE_SPRING: 1

volumes:
  db-data:
  bundle: